version: '3'

services:
    python:
        image: python:3.6
        volumes:
            - ./auth:/auth
        ports:
            - 8000:8000
        command: bash -c "cd ./auth && pip install -r requirements && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"