# Generated by Django 4.0.2 on 2022-03-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_remove_borrowed_to_who_remove_borrowed_what_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('projectId', models.CharField(max_length=100)),
            ],
        ),
    ]
