# Generated by Django 4.0.2 on 2022-04-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusers',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
